sudo: true
dist: xenial 
services:
  - docker
language: python 
python:
  - "3.4"

before_install:
  - pip3 install cwltool
  - docker build -t bionitio-python .

script:
  # Both of these same tests, in Docker
  # Functional tests
  - docker run --entrypoint /bionitio/.travis/unit-test.sh bionitio-python
  # Unit tests
  - docker run --entrypoint /bionitio/functional_tests/bionitio-test.sh bionitio-python -p bionitio -d /bionitio/functional_tests/test_data -v

  # CWL definition test
  - cwltool bionitio.cwl --fasta_file functional_tests/test_data/two_sequence.fasta
